[package]
name = "common-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["alloc"] }
log = { workspace = true }
golem-rust = { workspace = true, features = ["export_golem_agentic", "golem_ai"] }
serde = { workspace = true }
serde_json = { workspace = true }
wstd = { workspace = true }