[package]
name = "common-lib"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["alloc"] }
log = { workspace = true }
golem-rust = { workspace = true }
golem-ai-llm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wstd = { workspace = true }
