### Collect

POST http://journai.localhost:9006/collect/loki
Accept: application/json
Content-Type: application/json

{
  "entries": [
    {
      "boot_id":"f386e4aa97854312ad0f33cee927c973",
      "hostname":"loki",
      "machine_id":"2b9d4531fb3043e68d5d17371d0f97b3",
      "priority":"4",
      "message":"warning: mm_reap: preauth child terminated by signal 15",
      "date":1743859411.814896,
      "runtime_scope":"system",
      "pid":"3352307",
      "uid":"0",
      "gid":"0",
      "transport":"syslog",
      "syslog_facility":"4",
      "syslog_identifier":"sshd-session",
      "comm":"sshd-session",
      "exe":"/usr/lib/ssh/sshd-session",
      "cmdline":"\"sshd-session: s3th [priv]\"",
      "systemd_unit":"session-77.scope",
      "systemd_slice":"user-1000.slice",
      "systemd_cgroup":"/user.slice/user-1000.slice/session-77.scope",
      "invocation_id":"56bfa1e5ffb344e99081e9129c2525a7",
      "source_boottime_timestamp":"1743859411751069"
    },
    {
      "boot_id":"f386e4aa97854312ad0f33cee927c973",
      "hostname":"loki",
      "machine_id":"2b9d4531fb3043e68d5d17371d0f97b3",
      "priority":"3",
      "message":"error: mm_reap: preauth child terminated by signal 15",
      "date":1743859412.814896,
      "runtime_scope":"system",
      "pid":"3352307",
      "uid":"0",
      "gid":"0",
      "transport":"syslog",
      "syslog_facility":"4",
      "syslog_identifier":"sshd-session",
      "comm":"sshd-session",
      "exe":"/usr/lib/ssh/sshd-session",
      "cmdline":"\"sshd-session: s3th [priv]\"",
      "systemd_unit":"session-77.scope",
      "systemd_slice":"user-1000.slice",
      "systemd_cgroup":"/user.slice/user-1000.slice/session-77.scope",
      "invocation_id":"56bfa1e5ffb344e99081e9129c2525a7",
      "source_boottime_timestamp":"1743859411751069"
    }
  ]
}

### Fetch

GET http://journai.localhost:9006/entries/loki?since=-1&priority=-1&contains=



### Fetch (since)

GET http://journai.localhost:9006/entries/loki?since=1743859412&priority=-1&contains=



### Fetch (priority)

GET http://journai.localhost:9006/entries/loki?since=-1&priority=3&contains=



### Fetch (since & priority)

GET http://journai.localhost:9006/entries/loki?since=1743859412&priority=3&contains=



### Fetch (contains)

GET http://journai.localhost:9006/entries/loki?since=-1&priority=-1&contains=mm_reap%3A%20preauth

### Fetch (priority & contains)

GET http://journai.localhost:9006/entries/loki?since=-1&priority=3&contains=mm_reap%3A%20preauth

### Fetch (since & priority & contains)

GET http://journai.localhost:9006/entries/loki?since=1743859412&priority=3&contains=mm_reap%3A%20preauth

### Fetch error spikes

GET http://journai.localhost:9006/errors/loki

### Dashboard

GET http://journai.localhost:9006/dashboard/overview

### Dashboard alerts

GET http://journai.localhost:9006/dashboard/alerts

### Analysis queue

GET http://journai.localhost:9006/analysis/queue

### Analysis history loki

GET http://journai.localhost:9006/analysis/history/loki
