[package]
name = "journai_analyzer"
version = "1.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
common-lib = { path = "../../common-rust/common-lib" }

log = { workspace = true }
golem-rust = { workspace = true }
golem-ai-llm = { workspace = true }
golem-ai-llm-openrouter = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toon-format = { workspace = true }
wstd = { workspace = true }
